language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install

script:
  - vendor/bin/phpcs --standard=psr2 src -n
